# Gradle
org.gradle.warning.mode=none
# Dependencies
kotlin.code.style=official
kotlin_version=2.4.10
ktor_version=3.2.3
atomicfu_version=0.29.0
logback_version=1.5.22
syndication_kotlin=2.1.4
bucket4j_version=8.10.1
caffeine_version=3.2.3
jaikan_version=v2.1.2
assertj_version=3.27.6
mockk_version=1.14.7
jib_version=3.5.2
